#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.1 on Wed Jan  9 14:09:42 2008

import wx
import os
import time

# begin wxGlade: extracode
# end wxGlade



class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.texto_ruta_archivo = wx.TextCtrl(self, -1, "")
        self.boton_examinar = wx.Button(self, -1, "Examinar")
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("data/logo.png", wx.BITMAP_TYPE_ANY))
        self.boton_subir = wx.Button(self, -1, "Subir")
        self.texto_estado = wx.TextCtrl(self, -1, "Listo", style=wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.texto_subir_handler, self.texto_ruta_archivo)
        self.Bind(wx.EVT_BUTTON, self.examinar_handler, self.boton_examinar)
        self.Bind(wx.EVT_BUTTON, self.subir_handler, self.boton_subir)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Pyuploader")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_1.Add(self.texto_ruta_archivo, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.boton_examinar, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.boton_subir, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_4.Add(self.texto_estado, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def examinar_handler(self, event): # wxGlade: MyFrame1.<event_handler>
        self.texto_estado.SetBackgroundColour("#ffffff")
        print "Abrir ventana pare elegir ruta_archivo"
        self.texto_estado.SetValue("Abrir ventana pare elegir ruta_archivo")
        #event.Skip()

    def subir_handler(self, event): # wxGlade: MyFrame1.<event_handler>
        self.texto_estado.SetBackgroundColour("#ffffff")
        texto = "Validar ruta(con otro metodo). Subir el archivo. "
        if self.ruta_valida():
            texto = "Subir el archivo"
            #Subir el archivo
        else:
            texto = "La ruta no es valida"
            self.texto_estado.SetBackgroundColour("#ff0000")
        print texto
        self.texto_estado.SetValue(texto)
        #event.Skip()

    def ruta_valida(self):
        ruta = self.texto_ruta_archivo.GetValue()
        if os.path.isfile(ruta):
            return True

    def texto_handler(self, event): # wxGlade: MyFrame1.<event_handler>
        print "Event handler `texto_handler' not implemented"
        event.Skip()

    def texto_subir_handler(self, event): # wxGlade: MyFrame1.<event_handler>
        print "Event handler `texto_subir_handler' not implemented"
        event.Skip()

# end of class MyFrame1


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame1(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
